# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: default
  - model: biolord
  - callbacks: default
  - logger: default
  - trainer: default
  - paths: default
  - hydra: default
  
  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null #null

  # config for hyperparameter optimization
  - hpo: null

# task name, determines output directory path
task_name: "train"

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# which checkpoint to use for testing when multiple checkpoints are saved
# options: "loss" (use checkpoint with best val_loss_epoch), "pcc" (use checkpoint with best val_PCC_epoch), or "all" (test with all available checkpoints)
# only applies when train=True, otherwise use ckpt_path
test_ckpt_type: "loss"  # "loss", "pcc"

# simply provide checkpoint path to resume training or for testing (when train=False)
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null
