# path to data directory
# data_dir: ./notebooks/neurips2024/perturbench_data/
cfg_dir:
data_dir: /fs-computility-new/upzd_share/maoxinjie/wenqianhong/perturbench-main/notebooks/neurips2025/perturbench_data

# path to logging directory
# 使用绝对路径确保写到共享存储，而不是节点本地目录
log_dir: /fs-computility-new/upzd_share/maoxinjie/AIVC/mxj/perturbench-main/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
