_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 50 # prevents early stopping
max_epochs: 500

accelerator: gpu
devices: 1

precision: 32

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

deterministic: False

# log every N steps
log_every_n_steps: 10

# Gradient clipping to prevent exploding gradients in VAE
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
